{% set version = "5.6.0" %}

package:
  name: pymc
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/pymc/archive/v{{version}}.tar.gz
  sha256: 200a28469d574a370fa9b55cd92f112f8ad09f71674bdae514437039e953689b

build:
  number: 0
  script:
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - export LDFLAGS="$LDFLAGS -shared"  # [linux]
    - "python setup.py install"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - mkl-devel  {{ mkl }}      # [blas_impl == "mkl"]
    - openblas-devel {{ openblas }}  # [blas_impl == "openblas"]
    - numpy-devel  {{ numpy }}  # [not (osx and arm64) and py<=39]
    - numpy {{ numpy }}         # [(osx and arm64) or py>39]
    - pip
  run:
    - python
    - scipy
    - numpy-devel  {{ numpy }}  # [not (osx and arm64) and py<=39]
    - numpy {{ numpy }}         # [(osx and arm64) or py>39]

test:
  imports:
    - pymc
    - pymc.database
    - pymc.examples
    - pymc.gp
    - pymc.gp.cov_funs
    - pymc.Container_values
    - pymc.LazyFunction
    - pymc.flib
    - pymc.gp.cov_funs.distances
    - pymc.gp.cov_funs.isotropic_cov_funs
    - pymc.gp.incomplete_chol
    - pymc.gp.linalg_utils

about:
  home: http://github.com/pymc-devs/pymc
  license: AFL-3.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'PyMC: Bayesian Stochastic Modelling in Python'

  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain
    Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core
    sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence
    diagnostics.
  doc_url: http://pymc-devs.github.io/pymc/
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf
