{% set version = "4.0.1" %}

package:
  name: pymc-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz
  sha256: e69f2335e0cdb7205f8b80cadf1a5620cf9faef9c27175c09eb99c4839d0d182

build:
  number: 0
  skip: true  # [py<=37]

outputs:
  - name: pymc-base
    build:
      script:
        - python -m pip install . --no-deps -vv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
      run:
        - python
        # While libpython is an implicit dependency and will thus be installed
        # regardless of whether or not it's included here, it's also a direct
        # dependency of aesara, so we mention it explicitly.
        - libpython >=2.0  # [win]

        # https://github.com/pymc-devs/pymc/blob/v{{ version }}/requirements.txt
        - aeppl ==0.0.31
        - aesara-base ==2.7.4
        - arviz >=0.12.0
        - cachetools >=4.2.1
        - cloudpickle
        - fastprogress >=0.2.0
        - numpy >=1.15.0
        - scipy >=1.4.1
        - typing-extensions >=3.7.4
    test:
      imports:
        - pymc
        - pymc.backends
        - pymc.distributions
        - pymc.gp
        - pymc.step_methods
        - pymc.tests
        - pymc.tuning
        - pymc.variational
        - pymc.ode
      commands:
        - pip check
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt
  - name: pymc
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pymc-base", exact=True) }}
        # This last part with =*_1 is a temporary workaround since there are two
        # builds for aesara-base v2.7.4 labeled like xyz_1 and abc_2.
        # In the next version, we should change this line to be
        # "- aesara >=2.7.5". After this change, we should always get the correct
        # version of the "aesara" package automatically since the "aesara" package
        # pins to the "aesara-base" package of the exact same version number, and
        # thus will be constrained by the "aesara-base" package specified above.
        - aesara ==2.7.4=*_1
    test:
      imports:
        - pymc
        - pymc.backends
        - pymc.distributions
        - pymc.gp
        - pymc.step_methods
        - pymc.tests
        - pymc.tuning
        - pymc.variational
        - pymc.ode
      commands:
        - pip check
        - python check-for-warnings.py allowed-warnings-main.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: http://github.com/pymc-devs/pymc
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - twiecki
    - fonnesbeck
    - ocefpaf
    - michaelosthege
    - maresb
    - ricardoV94
