{% set python_min = "3.11" %}
{% set version = "5.26.0" %}

package:
  name: pymc-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pymc/pymc-{{ version }}.tar.gz
  sha256: 0cad467575106f16b7b7cc756e598ed7b1e641eda036947f23b8200a0d677ff3

build:
  number: 0

outputs:
  - name: pymc-base
    build:
      noarch: python
      script:
        - python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - versioneer ==0.29
        - pip
      run:
        - python >={{ python_min }}
        # https://github.com/pymc-devs/pymc/blob/v{{ version }}/requirements.txt
        - arviz >=0.13.0
        - cachetools >=4.2.1
        - cloudpickle
        - numpy >=1.25.0
        - pandas >=0.24.0
        - pytensor-base >=2.35.0,<2.36
        - rich >=13.7.1
        - scipy >=1.4.1
        - threadpoolctl >=3.1.0,<4.0.0
        - typing_extensions >=3.7.4
    test:
      imports:
        - pymc
        - pymc.backends
        - pymc.distributions
        - pymc.gp
        - pymc.step_methods
        - pymc.tuning
        - pymc.variational
        - pymc.ode
      commands:
        - pip check
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
        - python {{ python_min }}
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt
  - name: pymc
    build:
      noarch: python
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      run:
        - {{ pin_subpackage("pymc-base", exact=True) }}
        # In PyTensor, there is a 1-1 correspondence between the "pytensor-base"
        # package and the "pytensor" package of the same version and build number on
        # which it depends. Thus the pin from the "pytensor-base" package above will
        # implicitly transfer here to the "pytensor" package.
        - pytensor
        - python-graphviz
    test:
      imports:
        - pymc
        - pymc.backends
        - pymc.distributions
        - pymc.gp
        - pymc.step_methods
        - pymc.tuning
        - pymc.variational
        - pymc.ode
        - pymc.model_graph
      commands:
        - pip check
        - python check-for-warnings.py allowed-warnings-main.txt
      requires:
        - pip
        - python {{ python_min }}
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: http://github.com/pymc-devs/pymc
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - twiecki
    - fonnesbeck
    - ocefpaf
    - michaelosthege
    - maresb
    - ricardoV94
