{% set version = "4.0.0" %}

package:
  name: pymc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz
  sha256: 08cac213bf52d5a16b0aeef6ff6a312780a6a6ae935a2603fa607f4c105726af

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - aesara ==2.6.6
    - aeppl ==0.0.31
    - arviz >=0.12.0
    - cachetools >=4.2.1
    - cloudpickle
    - fastprogress >=0.2.0
    - numpy >=1.15.0
    - scipy >=1.4.1
    - typing-extensions >=3.7.4
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]

test:
  imports:
    - pymc
    - pymc.backends
    - pymc.distributions
    - pymc.gp
    - pymc.step_methods
    - pymc.tests
    - pymc.tuning
    - pymc.variational
    - pymc.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - twiecki
    - fonnesbeck
    - ocefpaf
    - michaelosthege
    - maresb
    - ricardoV94
