{% set version = "2.3.7" %}

package:
  name: pymc
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/pymc/archive/v{{version}}.tar.gz
  sha256: 12765987a5d64eaf210b1a32053990a0a4cacf2458e93d9b35ebab239032a4b5

build:
  number: 1003
  skip: True  # [win]
  skip: True  # [py>36]
  script:
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - pymc
    - pymc.database
    - pymc.examples
    - pymc.gp
    - pymc.gp.cov_funs
    - pymc.Container_values
    - pymc.LazyFunction
    - pymc.flib
    - pymc.gp.cov_funs.distances
    - pymc.gp.cov_funs.isotropic_cov_funs
    - pymc.gp.incomplete_chol
    - pymc.gp.linalg_utils

about:
  home: http://github.com/pymc-devs/pymc
  license: AFL-3.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'PyMC: Bayesian Stochastic Modelling in Python'

  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence diagnostics.
  doc_url: http://pymc-devs.github.io/pymc/
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf
