{% set version = "4.0.0b3" %}

package:
  name: pymc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz
  sha256: 185ad4a19a7870a38c35352f8169ae1d57637b8704bd3fa675f2b7d43a0c420d

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aesara ==2.5.0
    - aeppl ==0.0.27
    - arviz >=0.11.4
    - cachetools >=4.2.1
    - cloudpickle
    - fastprogress >=0.2.0
    - numpy >=1.15.0
    - pandas >=0.24.0
    - scipy >=1.4.1
    - semver
    - typing-extensions >=3.7.4
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]

test:
  imports:
    - pymc
    - pymc.backends
    - pymc.distributions
    - pymc.gp
    - pymc.step_methods
    - pymc.tests
    - pymc.tuning
    - pymc.variational
    - pymc.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - twiecki
    - fonnesbeck
    - ocefpaf
    - michaelosthege
    - maresb
